name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lint
        uses: devcontainers/ci@v0.2
        with:
          devcontainerPath: .devcontainer
          runCmd: "pnpm run lint"

  check:
    name: Svelte Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Check
        uses: devcontainers/ci@v0.2
        with:
          devcontainerPath: .devcontainer
          runCmd: "pnpm run check"

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Test
        uses: devcontainers/ci@v0.2
        with:
          devcontainerPath: .devcontainer
          runCmd: |
            pnpm run build &&
            pnpm run test
